// Curated scenario inspirations for Simulation and Survey pages
// Social research + insurance verticals, designed for Singapore context

export interface InspirationScenario {
  icon: string;
  title: string;
  titleZh: string;
  question: string;
  questionZh: string;
  options: string[];
  optionsZh: string[];
  context?: string;
  contextZh?: string;
  category: 'policy' | 'social' | 'finance' | 'health' | 'consumer';
}

// ─── Simulation inspirations (social/policy focus) ───
export const SIMULATION_SCENARIOS: InspirationScenario[] = [
  // Policy
  {
    icon: '💰',
    title: 'CPF Withdrawal Age',
    titleZh: 'CPF 提取年龄',
    category: 'policy',
    question: 'The government proposes raising the CPF withdrawal age from 55 to 60, with enhanced interest rates. What is your position?',
    questionZh: '政府提议将 CPF 提取年龄从 55 岁提高到 60 岁，同时提高利率。你什么立场？',
    options: ['Strongly support', 'Somewhat support', 'Neutral', 'Somewhat oppose', 'Strongly oppose'],
    optionsZh: ['强烈支持', '比较支持', '中立', '比较反对', '强烈反对'],
    context: 'CPF Ordinary Account interest: 2.5%, Special Account: 4%. Average CPF balance at 55: ~S$200K. Life expectancy: 84 years.',
    contextZh: 'CPF 普通账户利率 2.5%，特别账户 4%。55 岁平均 CPF 余额约 S$20 万。预期寿命 84 岁。',
  },
  {
    icon: '🏠',
    title: 'HDB 99-Year Lease',
    titleZh: 'HDB 99 年地契',
    category: 'policy',
    question: 'Should the government offer SERS (Selective En bloc Redevelopment Scheme) guarantee for all HDB flats reaching 60 years?',
    questionZh: '政府是否应该为所有达到 60 年的 HDB 组屋提供 SERS（选择性整体重建计划）保证？',
    options: ['Strongly agree', 'Somewhat agree', 'Neutral', 'Somewhat disagree', 'Strongly disagree'],
    optionsZh: ['非常同意', '比较同意', '中立', '比较不同意', '非常不同意'],
    context: 'HDB 99-year leasehold. ~10,000 units over 50 years old. SERS eligibility is selective. Median resale price for old flats drops significantly after 40+ years.',
    contextZh: 'HDB 99 年地契。约 1 万套超过 50 年。SERS 资格是选择性的。老组屋 40 年后转售价大幅下降。',
  },
  {
    icon: '🪖',
    title: 'NS Duration Reform',
    titleZh: '国民服役改革',
    category: 'policy',
    question: 'Should National Service be shortened from 24 to 18 months, with an extended reservist obligation?',
    questionZh: '国民服役是否应从 24 个月缩短至 18 个月，同时延长战备军人义务？',
    options: ['Strongly support', 'Somewhat support', 'Neutral', 'Somewhat oppose', 'Strongly oppose'],
    optionsZh: ['强烈支持', '比较支持', '中立', '比较反对', '强烈反对'],
    context: 'SAF active personnel: ~72,000. Annual enlistees: ~20,000. Reservist cycle: 10 years. Regional security concerns persist.',
    contextZh: 'SAF 现役约 7.2 万。每年入伍约 2 万人。战备军人周期 10 年。区域安全问题持续存在。',
  },
  {
    icon: '🌍',
    title: 'Immigration Cap',
    titleZh: '移民配额',
    category: 'policy',
    question: 'Should Singapore cap new PR approvals at 20,000/year (vs current ~30,000) to address housing and job competition concerns?',
    questionZh: '新加坡是否应将每年新 PR 批准限制在 2 万人（现约 3 万），以缓解住房和就业竞争？',
    options: ['Strongly agree', 'Somewhat agree', 'Neutral', 'Somewhat disagree', 'Strongly disagree'],
    optionsZh: ['非常同意', '比较同意', '中立', '比较不同意', '非常不同意'],
    context: 'Singapore population: 5.92M (3.61M citizens, 0.54M PRs, 1.77M non-residents). ~32,000 new PRs granted in 2023.',
    contextZh: '新加坡人口 592 万（公民 361 万，PR 54 万，非居民 177 万）。2023 年约 3.2 万新 PR 获批。',
  },
  // Social
  {
    icon: '🎓',
    title: 'PSLE Streaming',
    titleZh: 'PSLE 分流制度',
    category: 'social',
    question: 'Has the shift from PSLE T-score to Achievement Level (AL) system reduced academic pressure on primary school students?',
    questionZh: 'PSLE 从 T-score 改为积分等级制（AL）是否减轻了小学生的学业压力？',
    options: ['Significantly reduced', 'Somewhat reduced', 'No change', 'Somewhat increased', 'Don\'t know'],
    optionsZh: ['明显减轻', '有所减轻', '没有变化', '反而增加', '不清楚'],
    context: 'PSLE AL system introduced 2021. Scores range 4-32 (lower=better). Tuition industry worth ~S$1.4B/year.',
    contextZh: 'PSLE 积分制 2021 年推出。分数 4-32（越低越好）。补习行业年值约 S$14 亿。',
  },
  {
    icon: '🏳️‍🌈',
    title: '377A Aftermath',
    titleZh: '377A 废除后续',
    category: 'social',
    question: 'After repealing Section 377A, should the government also legalize same-sex civil unions?',
    questionZh: '废除 377A 条款后，政府是否应进一步合法化同性民事结合？',
    options: ['Yes, full marriage', 'Civil unions only', 'Status quo is fine', 'Should not have repealed', 'No opinion'],
    optionsZh: ['是，完全婚姻平权', '仅民事结合', '现状就好', '不应该废除', '没有意见'],
    context: 'Section 377A repealed Dec 2022. Constitutional amendment protects marriage definition as man-woman. Public opinion divided along age/religion lines.',
    contextZh: '377A 于 2022 年 12 月废除。宪法修正案保护婚姻定义为一男一女。公众意见沿年龄/宗教分化。',
  },
  {
    icon: '🚇',
    title: 'COE System Reform',
    titleZh: 'COE 制度改革',
    category: 'social',
    question: 'Should Singapore replace the COE (Certificate of Entitlement) system with a road usage pricing model?',
    questionZh: '新加坡是否应该用道路使用定价模型取代 COE（拥车证）制度？',
    options: ['Strongly support', 'Somewhat support', 'Neutral', 'Somewhat oppose', 'Strongly oppose'],
    optionsZh: ['强烈支持', '比较支持', '中立', '比较反对', '强烈反对'],
    context: 'COE prices hit S$150,000+ for Cat A. Vehicle population: ~980,000. Public transport mode share: ~66%. ERP 2.0 satellite-based system launching.',
    contextZh: 'A 类 COE 价格突破 S$15 万。汽车总量约 98 万辆。公共交通出行比例约 66%。ERP 2.0 卫星系统即将启用。',
  },
  {
    icon: '☠️',
    title: 'Death Penalty',
    titleZh: '死刑存废',
    category: 'social',
    question: 'Should Singapore abolish the mandatory death penalty for drug trafficking and replace it with judicial discretion?',
    questionZh: '新加坡是否应废除贩毒强制死刑，改为法官自由裁量？',
    options: ['Abolish completely', 'Judicial discretion', 'Keep mandatory', 'Increase penalties', 'No opinion'],
    optionsZh: ['完全废除', '法官自由裁量', '保留强制死刑', '加重处罚', '没有意见'],
    context: 'Singapore executed ~15 people for drug offences since 2022. International pressure from EU and UN. Deterrence argument vs. human rights debate.',
    contextZh: '2022 年以来新加坡处决约 15 名毒品犯。欧盟和联合国施压。威慑论 vs 人权辩论。',
  },
  // Health
  {
    icon: '🏥',
    title: 'Public Hospital Wait',
    titleZh: '公立医院排队',
    category: 'health',
    question: 'Would you pay S$50-100 more per visit to guarantee a specialist appointment within 2 weeks at public hospitals?',
    questionZh: '你是否愿意每次多付 S$50-100，以保证在公立医院 2 周内获得专科预约？',
    options: ['Yes, definitely', 'Probably yes', 'Depends on condition', 'Probably no', 'No, wait is fine'],
    optionsZh: ['肯定愿意', '可能愿意', '看病情', '可能不愿意', '不愿意，等就好'],
    context: 'Median specialist wait time at public hospitals: 4-8 weeks. Private sector: 1-2 weeks but 3-5x cost. Government subsidizes up to 80% for citizens.',
    contextZh: '公立医院专科中位等待时间 4-8 周。私立 1-2 周但费用 3-5 倍。政府为公民补贴高达 80%。',
  },
  {
    icon: '🧠',
    title: 'Mental Health Support',
    titleZh: '心理健康支持',
    category: 'health',
    question: 'Should the government provide free mental health counseling sessions (6 per year) for all residents aged 15-35?',
    questionZh: '政府是否应为所有 15-35 岁居民提供免费心理咨询（每年 6 次）？',
    options: ['Strongly support', 'Somewhat support', 'Neutral', 'Somewhat oppose', 'Strongly oppose'],
    optionsZh: ['强烈支持', '比较支持', '中立', '比较反对', '强烈反对'],
    context: 'Youth suicide rate increased 50% in 5 years. Average counseling cost: S$120-200/session. IMH wait time: 2-3 months.',
    contextZh: '青少年自杀率 5 年增长 50%。平均咨询费用 S$120-200/次。心理卫生学院等待时间 2-3 个月。',
  },
];

// ─── Survey inspirations (insurance + market research focus) ───
export const SURVEY_SCENARIOS: InspirationScenario[] = [
  // Finance / Insurance
  {
    icon: '🏥',
    title: 'IP Premium Hike',
    titleZh: '综合健保涨价',
    category: 'finance',
    question: 'If your Integrated Shield Plan premium increases by 20% next year, what would you do?',
    questionZh: '如果你的综合健保计划（IP）保费明年涨 20%，你会怎么做？',
    options: ['Keep current plan', 'Downgrade to lower ward', 'Switch insurer', 'Drop IP, keep MediShield only', 'Undecided'],
    optionsZh: ['保留现有计划', '降级到更低病房等级', '更换保险公司', '退保 IP，只保 MediShield', '未决定'],
    context: 'Average IP premium for 40-year-old: S$800-1,200/year (private hospital). MediShield Life covers Class B2/C wards. Claims ratio: 85%.',
    contextZh: '40 岁 IP 平均保费 S$800-1,200/年（私立医院）。MediShield Life 覆盖 B2/C 级病房。赔付率 85%。',
  },
  {
    icon: '📋',
    title: 'Claims Experience',
    titleZh: '理赔体验',
    category: 'finance',
    question: 'What is the most frustrating part of the insurance claims process?',
    questionZh: '保险理赔过程中最令你不满的是什么？',
    options: ['Too much paperwork', 'Slow processing', 'Unclear coverage', 'Low payout vs expectation', 'Denied claim', 'No issues'],
    optionsZh: ['太多文件手续', '处理速度慢', '保障范围不清楚', '赔付低于预期', '理赔被拒', '没有问题'],
    context: 'LIA Singapore: average motor claim processing 10-14 days. Health claim: 5-10 days. 12% of claims disputed in 2023.',
    contextZh: 'LIA 新加坡：车险理赔平均 10-14 天。健康险 5-10 天。2023 年 12% 理赔有争议。',
  },
  {
    icon: '📱',
    title: 'Digital Insurance',
    titleZh: '数字化保险',
    category: 'finance',
    question: 'Would you buy a life insurance policy entirely online without meeting an agent?',
    questionZh: '你是否愿意完全在线上购买人寿保险，不需要见代理人？',
    options: ['Yes, prefer online', 'Yes, if cheaper', 'Need some guidance', 'Prefer agent', 'No, too risky'],
    optionsZh: ['是，更喜欢线上', '是，如果更便宜的话', '需要一些指导', '更喜欢代理人', '不会，太冒险'],
    context: 'Insurtech penetration in SG: growing 30% YoY. FWD, Singlife offer direct-to-consumer. Traditional agent force: ~30,000.',
    contextZh: '新加坡保险科技渗透率年增 30%。FWD、Singlife 提供直销。传统代理人约 3 万人。',
  },
  {
    icon: '👴',
    title: 'Elderly Care Insurance',
    titleZh: '老年护理保险',
    category: 'finance',
    question: 'Would you pay S$50-80/month for long-term care insurance that covers nursing home and home care costs?',
    questionZh: '你是否愿意每月支付 S$50-80 购买长期护理保险，覆盖养老院和居家护理费用？',
    options: ['Yes, essential', 'Probably yes', 'Need more info', 'Too expensive', 'Government should cover this'],
    optionsZh: ['是，很必要', '可能会', '需要更多信息', '太贵了', '政府应该承担'],
    context: 'CareShield Life: mandatory from 2020, basic coverage S$600/month. Nursing home cost: S$2,000-4,000/month. 1 in 2 healthy Singaporeans may need LTC.',
    contextZh: 'CareShield Life 2020 年起强制，基本覆盖 S$600/月。养老院费用 S$2,000-4,000/月。健康国人中每 2 人有 1 人可能需要长期护理。',
  },
  {
    icon: '💎',
    title: 'ILP Trust Crisis',
    titleZh: 'ILP 信任危机',
    category: 'finance',
    question: 'After recent ILP (Investment-Linked Policy) controversies, how has your trust in insurance-linked investments changed?',
    questionZh: '近期投连险（ILP）争议后，你对保险投资产品的信任有何变化？',
    options: ['Trust increased', 'No change', 'Somewhat decreased', 'Significantly decreased', 'Never trusted ILPs'],
    optionsZh: ['信任增加', '没有变化', '有所下降', '大幅下降', '从未信任过 ILP'],
    context: 'MAS issued guidelines on ILP sales practices. Average ILP annual fees: 2-4%. Complaints to FIDReC about ILPs rose 40% in 2023.',
    contextZh: 'MAS 发布 ILP 销售指引。ILP 平均年费 2-4%。2023 年 FIDReC 收到的 ILP 投诉增加 40%。',
  },
  // Consumer
  {
    icon: '🛒',
    title: 'Grocery Spending',
    titleZh: '杂货消费',
    category: 'consumer',
    question: 'With rising food costs, how have you changed your grocery shopping habits in the past year?',
    questionZh: '随着食品成本上升，过去一年你的杂货购物习惯有何变化？',
    options: ['Buy more house brands', 'Shop at cheaper stores', 'Reduce spending', 'No change', 'Buy more online', 'Grow own food'],
    optionsZh: ['买更多自有品牌', '去更便宜的商店', '减少消费', '没有变化', '更多网上购买', '自己种菜'],
    context: 'SG food inflation 4.1% in 2024. Supermarket market share: FairPrice 60%, Sheng Siong 15%, Cold Storage 10%. Online grocery grew 25% post-COVID.',
    contextZh: '新加坡 2024 年食品通胀 4.1%。超市市占：FairPrice 60%，昇菘 15%，Cold Storage 10%。线上杂货疫后增长 25%。',
  },
  {
    icon: '🏘️',
    title: 'BTO vs Resale',
    titleZh: 'BTO vs 转售',
    category: 'consumer',
    question: 'If you are a first-time homebuyer, would you choose BTO (wait 4-5 years) or resale HDB (immediate)?',
    questionZh: '如果你是首次购房者，你会选择 BTO（等 4-5 年）还是转售 HDB（立即入住）？',
    options: ['BTO definitely', 'BTO if good location', 'Resale for speed', 'Resale for location', 'Cannot afford either', 'Private property'],
    optionsZh: ['一定选 BTO', 'BTO 如果地段好', '转售因为快', '转售因为地段', '两个都买不起', '买私人公寓'],
    context: 'BTO wait: 4-5 years. BTO 4-room: S$300-500K (before grants). Resale 4-room: S$500-700K. First-timer grants up to S$80K.',
    contextZh: 'BTO 等候 4-5 年。BTO 四房 S$30-50 万（补贴前）。转售四房 S$50-70 万。首次购房补贴最高 S$8 万。',
  },
  {
    icon: '✈️',
    title: 'Travel Insurance',
    titleZh: '旅行保险',
    category: 'finance',
    question: 'What is the main factor when choosing travel insurance?',
    questionZh: '选择旅行保险时，最重要的因素是什么？',
    options: ['Price', 'Medical coverage amount', 'Trip cancellation cover', 'Brand reputation', 'Easy claims process', 'COVID coverage'],
    optionsZh: ['价格', '医疗保障金额', '行程取消保障', '品牌声誉', '理赔便捷', 'COVID 保障'],
    context: 'Changi Airport: 65.5M passengers in 2024. Average travel insurance: S$30-80 per trip. 15% of travelers don\'t buy insurance.',
    contextZh: '樟宜机场 2024 年客流 6,550 万。平均旅行保险 S$30-80/次。15% 旅客不买保险。',
  },
  // Health
  {
    icon: '💊',
    title: 'TCM vs Western Medicine',
    titleZh: '中医 vs 西医',
    category: 'health',
    question: 'For chronic pain management, which approach do you prefer?',
    questionZh: '对于慢性疼痛管理，你更倾向哪种方式？',
    options: ['Western medicine only', 'Mainly western, some TCM', 'Equal mix', 'Mainly TCM', 'TCM only', 'Neither'],
    optionsZh: ['仅西医', '主要西医，辅以中医', '各一半', '主要中医', '仅中医', '都不'],
    context: 'Singapore has 2,800+ registered TCM practitioners. TCM not covered by most IPs. CHAS subsidizes TCM for lower-income.',
    contextZh: '新加坡有 2,800 多名注册中医师。大多数 IP 不覆盖中医。CHAS 为低收入群体补贴中医。',
  },
  {
    icon: '🩺',
    title: 'Preventive Health',
    titleZh: '预防性健康',
    category: 'health',
    question: 'Would you participate in a government-subsidized annual comprehensive health screening (S$50 co-pay)?',
    questionZh: '你是否愿意参加政府补贴的年度全面健康检查（自付 S$50）？',
    options: ['Yes, every year', 'Yes, every 2 years', 'Only if free', 'Prefer private clinic', 'Not interested'],
    optionsZh: ['是，每年都参加', '是，每 2 年', '免费才参加', '更喜欢去私立诊所', '不感兴趣'],
    context: 'Screen for Life: subsidized screening for 40+ citizens. Chronic disease prevalence: diabetes 8.8%, hypertension 21.6%. Early detection reduces treatment cost by 60%.',
    contextZh: 'Screen for Life：40 岁以上公民补贴筛查。慢病患病率：糖尿病 8.8%，高血压 21.6%。早期发现降低 60% 治疗成本。',
  },
];

// Category labels for sidebar grouping
export const CATEGORY_LABELS: Record<string, { en: string; zh: string }> = {
  policy: { en: 'Policy & Governance', zh: '政策与治理' },
  social: { en: 'Social Issues', zh: '社会议题' },
  finance: { en: 'Finance & Insurance', zh: '金融与保险' },
  health: { en: 'Healthcare', zh: '医疗健康' },
  consumer: { en: 'Consumer & Lifestyle', zh: '消费与生活' },
};
